name: Deploy backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      
      - name: Create .env file
        run: |
          touch .env
          echo PORT=${{secrets.PORT}} >> .env
          echo DATABASE_URL="${{secrets.DATABASE_URL}}" >> .env
          echo PRISMA_SCHEMA=src/db/schema.prisma >> .env
          cat .env
      
      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install repo dependencies
        run: bun install

      - name: Run prisma migrations
        run: bun prisma migrate deploy
      
      - name: Compile backend
        run: bun run build
      
      - name: Upload compiled code
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: './build/'
          server-dir: 'build/'
      
      - name: Connect to the server and start production
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/html
            pm2 delete server || true  # Detener la aplicación anterior si existe
            pm2 start --interpreter bun build/server.ts